---
title: "First Knit"
author: "Gael Gonzalez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended at William J. Pete Knight High School. English mostly talks about literature, summarize the book or articles you read, and write couple of essays. Math is solving problems, graphing, and adding, subtracting, multiplying, and dividing numbers and variables. I am best in math and hope I do good in this class. I suck at English in work and public speaking and I'm really good at math surprisingly.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
  My laptop is HP Chromebook x360. I would rate myself like 5 or 6 because I know some about computers but don't know much about coding or this stuff. My internet connection is perfect.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   My name is Gael and it's a Spanish name and it's pronounce Ga-El. My friends call me Gil because it's simple and easier. I'm used to be called Gil, so it's their and your choice.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
I want to transfer to Cal State University of Bakersfield by Fall 2023 and graduate the university by Spring 2025 with a Bachelors in Business Administration. I'm interested in Business Administration for now and I hope I like it and do well and get my Bachelor's.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  I haven't gone to any foreign countries but I think this year, my family and I might go to Mexico for Christmas where all my relatives live. I haven't been in the military and if I had to choose which branch, I would chose marines because my friend told much about marines and I was planning to join but I didn't.




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I didn't take Math 115 or 116 before, so this is my first time taking Math 116. I know Math 115 is general education requirement but I didn't know about Math 116. Since I'm good at math but also this different than what I'm use to, I'm going to try to go for a "A" or a "B" in the class. My plan is just go with the flow and just focus and do the work.
 






  




